### ISSUE TITLE
Tables not working

### ISSUE THREAD

**Issue by jonpas** [AlfredoRamos/phpbb-ext-markdown#14] opened 2019-07-06 00:06 UTC
phpBB Markdown Version: `dev` (`6715a8298c28f00de9600234dc660fcee0059d9a`)

Tables as documented don't seem to work.

```
| Left | Center | Right |
|:-----|:------:|------:|
|   x  |    x   |   x   |
```
results in:
```
LeftCenterRightxxx
```

Tried with BBCode enabled and disabled.

**Comment by AlfredoRamos** [comment] 2019-07-07 14:49
Which extensions (with versions) do you have enabled?

Mmm... it think the tables parser is working, but the styling is not, otherwise you would get it as plain text. Which style do you use? does it inherit from prosilver?

Could you share the HTML output you get with the inspector?

**Comment by jonpas** [comment] 2019-07-07 14:55
> Which extensions (with versions) do you have enabled?

![](https://i.imgur.com/UNmbXt1.png)

> Which style do you use? does it inherit from prosilver?

[Milk v2](https://themeforest.net/item/milk-multipurpose-responsive-phpbb-31-theme/16119149)

> Could you share the HTML output you get with the inspector?

```html
<div class="content">
  LeftCenterRightxxx
  <table>
    <thead>
      <tr></tr>
    </thead>
    <tbody>
      <tr></tr>
    </tbody>
  </table>
</div>
```

**Comment by AlfredoRamos** [comment] 2019-07-07 15:13
That's weird.

Try the following:

```
Left | Center | Right
:-|:-:|-:
x | x | x
```

Any errors in the ACP or in the web server logs?

I haven't seen that kind of problems with TextFormatter, I would need to investigate because I can't reproduce that problem and I just noted there's no functional test for tables.

**Comment by jonpas** [comment] 2019-07-07 16:32
> Try the following:

Same result.

> Any errors in the ACP or in the web server logs?

None in ACP and none in Apache/PHP logs.

**Comment by AlfredoRamos** [comment] 2019-07-08 02:57
Have you modified the phpBB package in any way? I mean PHP files. The tables passed the unit tests, I'm not sure what could be wrong.

If you have SSH access and composer installed, please run the following commands in that server and post its content:

```shell
composer diagnose
composer show s9e/text-formatter
```

You can remove private information (paths) if you want, I only need versions (detected by the script) and hashes from `source` and `dist`

**Comment by jonpas** [comment] 2019-07-08 11:05
> Have you modified the phpBB package in any way? I mean PHP files.

No. I have only modified `markdown.css` before you merged the polls fix.

```bash
[snip@snip forum]$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Composer version: 1.7.2
PHP version: 5.4.7 - Package overridden via config.platform (actual: 7.2.19)
PHP binary path: /snippath/usr/bin/php
```

```bash
[snip@snip forum]$ composer show s9e/text-formatter
name     : s9e/text-formatter
descrip. : Multi-purpose text formatting and markup library. Plugins offer support for BBCodes, Markdown, emoticons, HTML, embedding media (YouTube, etc...), enhanced typography and more.
keywords : bbcode, bbcodes, blog, censor, embed, emoji, emoticons, engine, forum, html, markdown, markup, media, parser, shortcodes
versions : * 1.4.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/s9e/TextFormatter.git dc7efff70b67b9cee00881ad3bef0a1da076b31e
dist     : [zip] https://api.github.com/repos/s9e/TextFormatter/zipball/dc7efff70b67b9cee00881ad3bef0a1da076b31e dc7efff70b67b9cee00881ad3bef0a1da076b31e
names    : s9e/text-formatter

autoload
psr-4
s9e\TextFormatter\ => src

requires
ext-dom *
ext-filter *
lib-pcre >=7.2
php >=5.4.7

requires (dev)
matthiasmullie/minify *
php-coveralls/php-coveralls *
s9e/regexp-builder 1.*

suggests
ext-curl Improves the performance of the MediaEmbed plugin and some JavaScript minifiers
ext-intl Allows international URLs to be accepted by the URL filter
ext-json Enables the generation of a JavaScript parser
ext-mbstring Improves the performance of the PHP renderer
ext-tokenizer Improves the performance of the PHP renderer
ext-xsl Enables the XSLT renderer
ext-zlib Enables gzip compression when scraping content via the MediaEmbed plugin
```

**Comment by AlfredoRamos** [comment] 2019-07-08 13:56
Can you try with only Markdown extension enabled?

**Comment by jonpas** [comment] 2019-07-08 18:26
Disabled all extensions except Markdown, same result.

**Comment by AlfredoRamos** [comment] 2019-07-08 23:06
I fear I can't help you further about this issue, I would suggest to report it to the TextFormatter library giving as much information about your server setup as you can.

I can't reproduce your issue and even the tests pass, and with the given information it doesn't seems to be a extension conflict.

I'm sure JoshyPHP can help you better since he's the author of the library I'm using.

**Comment by jonpas** [comment] 2019-07-09 01:08
Sounds good, thanks!

**Comment by AlfredoRamos** [comment] 2019-07-10 03:37
Oh, I forgot, this is his repository:

https://github.com/s9e/TextFormatter

I'm closing this since it doesn't seems to be a issue of this extension.

**Closed by AlfredoRamos** 2019-07-10 03:37 UTC

**Comment by jonpas** [comment] 2019-07-10 04:04
Yes, I am aware, but thanks! :)
